version: '3'

services:
  webdav-monitor:
    image: fengmiemie/webdav-monitor:latest
    container_name: webdav-monitor
    restart: unless-stopped
    # 移除 network_mode: "host" 以解决sysctl错误
    # 添加IPv6支持
    networks:
      - ipv6_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - WEBDAV_URL=${WEBDAV_URL:-http://hu.miemiejun.me:5005}
      - WEBDAV_USERNAME=${WEBDAV_USERNAME:-19965027242}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD:-zhao131496}
      - WEBDAV_REMOTE_DIR=${WEBDAV_REMOTE_DIR:-/links/影视}
      - LOCAL_DIR=/data
      - THREADS=10
      - CHECK_INTERVAL=600
      - REPLACE_IP=hu.miemiejun.me
      - VERBOSE=true
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=
    volumes:
      - ${DATA_DIR:-/volume1/media/影视}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - "hu.miemiejun.me:2409:8a30:4f0:73b1:63b6:e88d:f1a:faef"

# 添加支持IPv6的网络配置
networks:
  ipv6_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:1::/64
          gateway: 2001:db8:1::1
    driver_opts:
      com.docker.network.enable_ipv6: "true" 